name: exchange
description: Provides a set of standardized APIs for exchanges and trading markets.
version: 0.0.1
repository: https://github.com/xclud/dart_exchange

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  decimal: ^2.2.0

dev_dependencies:
  test: ^1.21.5
  lints: ^2.0.0